name: mi_app_imgsound
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/acento.mp3
    - assets/sounds/silencio.mp3
    - assets/sounds/conteo1.mp3
    - assets/sounds/conteo2.mp3
    - assets/sounds/conteo3.mp3
    - assets/sounds/conteo4.mp3
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700