name: mi_app_imgsound
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/acento.mp3
    - assets/sounds/silencio.mp3
    - assets/sounds/conteo1.mp3
    - assets/sounds/conteo2.mp3
    - assets/sounds/conteo3.mp3
    - assets/sounds/conteo4.mp3
    - assets/images/bosquef.png
    - assets/images/bosquet.png
    - assets/images/textura.png
    - assets/images/textura_2.png
    - assets/images/textura_3.png
    - assets/images/pintando.png
    - assets/images/ritmo.png
    - assets/images/icon_lienzo.png
    - assets/images/icon_atras.png
    - assets/images/coin_yellow.png
    - assets/images/icon_home.png
    - assets/images/personam.png
    - assets/images/icon_menu.png
    - assets/images/icon_teoria.png
    - assets/sounds/escmayor.mp3
    - assets/sounds/escmenor.mp3
    - assets/sounds/esccromatica.mp3
    - assets/sounds/modofrigio.mp3
    - assets/sounds/eschexatonica.mp3
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700